name: cosmos-sdk-proto

on:
  push:
    branches: main
  pull_request:
    paths:
      - ".github/workflows/cosmos-sdk-proto.yml"
      - "cosmos-sdk-proto/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: cosmos-sdk-proto

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -Dwarnings

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.72.0 # MSRV
        target:
          - x86_64-unknown-linux-gnu
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features grpc

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.72.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test --release
