name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
[![Rust](https://github.com/cosmos/ics23/actions/workflows/rust.yml/badge.svg)](https://github.com/cosmos/ics23/actions/workflows/rust.yml)
