// @generated
// This file is @generated by prost-build.
/// Minter represents the minting state.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Minter {
    /// current annual inflation rate
    #[prost(string, tag = "1")]
    pub inflation: ::prost::alloc::string::String,
    /// current annual expected provisions
    #[prost(string, tag = "2")]
    pub annual_provisions: ::prost::alloc::string::String,
}
impl ::prost::Name for Minter {
    const NAME: &'static str = "Minter";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.Minter".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.Minter".into()
    }
}
/// Params defines the parameters for the x/mint module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Params {
    /// type of coin to mint
    #[prost(string, tag = "1")]
    pub mint_denom: ::prost::alloc::string::String,
    /// maximum annual change in inflation rate
    #[prost(string, tag = "2")]
    pub inflation_rate_change: ::prost::alloc::string::String,
    /// maximum inflation rate
    #[prost(string, tag = "3")]
    pub inflation_max: ::prost::alloc::string::String,
    /// minimum inflation rate
    #[prost(string, tag = "4")]
    pub inflation_min: ::prost::alloc::string::String,
    /// goal of percent bonded atoms
    #[prost(string, tag = "5")]
    pub goal_bonded: ::prost::alloc::string::String,
    /// expected blocks per year
    #[prost(uint64, tag = "6")]
    pub blocks_per_year: u64,
}
impl ::prost::Name for Params {
    const NAME: &'static str = "Params";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.Params".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.Params".into()
    }
}
/// GenesisState defines the mint module's genesis state.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GenesisState {
    /// minter is a space for holding current inflation information.
    #[prost(message, optional, tag = "1")]
    pub minter: ::core::option::Option<Minter>,
    /// params defines all the parameters of the module.
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for GenesisState {
    const NAME: &'static str = "GenesisState";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.GenesisState".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.GenesisState".into()
    }
}
/// QueryParamsRequest is the request type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryParamsRequest {}
impl ::prost::Name for QueryParamsRequest {
    const NAME: &'static str = "QueryParamsRequest";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryParamsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryParamsRequest".into()
    }
}
/// QueryParamsResponse is the response type for the Query/Params RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryParamsResponse {
    /// params defines the parameters of the module.
    #[prost(message, optional, tag = "1")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for QueryParamsResponse {
    const NAME: &'static str = "QueryParamsResponse";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryParamsResponse".into()
    }
}
/// QueryInflationRequest is the request type for the Query/Inflation RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryInflationRequest {}
impl ::prost::Name for QueryInflationRequest {
    const NAME: &'static str = "QueryInflationRequest";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryInflationRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryInflationRequest".into()
    }
}
/// QueryInflationResponse is the response type for the Query/Inflation RPC
/// method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryInflationResponse {
    /// inflation is the current minting inflation value.
    #[prost(bytes = "vec", tag = "1")]
    pub inflation: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for QueryInflationResponse {
    const NAME: &'static str = "QueryInflationResponse";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryInflationResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryInflationResponse".into()
    }
}
/// QueryAnnualProvisionsRequest is the request type for the
/// Query/AnnualProvisions RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct QueryAnnualProvisionsRequest {}
impl ::prost::Name for QueryAnnualProvisionsRequest {
    const NAME: &'static str = "QueryAnnualProvisionsRequest";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryAnnualProvisionsRequest".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryAnnualProvisionsRequest".into()
    }
}
/// QueryAnnualProvisionsResponse is the response type for the
/// Query/AnnualProvisions RPC method.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct QueryAnnualProvisionsResponse {
    /// annual_provisions is the current minting annual provisions value.
    #[prost(bytes = "vec", tag = "1")]
    pub annual_provisions: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for QueryAnnualProvisionsResponse {
    const NAME: &'static str = "QueryAnnualProvisionsResponse";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.QueryAnnualProvisionsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.QueryAnnualProvisionsResponse".into()
    }
}
/// MsgUpdateParams is the Msg/UpdateParams request type.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MsgUpdateParams {
    /// authority is the address that controls the module (defaults to x/gov unless overwritten).
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
    /// params defines the x/mint parameters to update.
    ///
    /// NOTE: All parameters must be supplied.
    #[prost(message, optional, tag = "2")]
    pub params: ::core::option::Option<Params>,
}
impl ::prost::Name for MsgUpdateParams {
    const NAME: &'static str = "MsgUpdateParams";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.MsgUpdateParams".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.MsgUpdateParams".into()
    }
}
/// MsgUpdateParamsResponse defines the response structure for executing a
/// MsgUpdateParams message.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct MsgUpdateParamsResponse {}
impl ::prost::Name for MsgUpdateParamsResponse {
    const NAME: &'static str = "MsgUpdateParamsResponse";
    const PACKAGE: &'static str = "cosmos.mint.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.mint.v1beta1.MsgUpdateParamsResponse".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.mint.v1beta1.MsgUpdateParamsResponse".into()
    }
}
include!("cosmos.mint.v1beta1.serde.rs");
include!("cosmos.mint.v1beta1.tonic.rs");
// @@protoc_insertion_point(module)
