// @generated
// This file is @generated by prost-build.
/// LegacyAminoPubKey specifies a public key type
/// which nests multiple public keys and a threshold,
/// it uses legacy amino address rules.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LegacyAminoPubKey {
    #[prost(uint32, tag = "1")]
    pub threshold: u32,
    #[prost(message, repeated, tag = "2")]
    pub public_keys: ::prost::alloc::vec::Vec<::tendermint_proto::google::protobuf::Any>,
}
impl ::prost::Name for LegacyAminoPubKey {
    const NAME: &'static str = "LegacyAminoPubKey";
    const PACKAGE: &'static str = "cosmos.crypto.multisig";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.crypto.multisig.LegacyAminoPubKey".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.crypto.multisig.LegacyAminoPubKey".into()
    }
}
include!("cosmos.crypto.multisig.serde.rs");
// @@protoc_insertion_point(module)
