// @generated
// This file is @generated by prost-build.
/// PubKey defines a secp256k1 public key
/// Key is the compressed form of the pubkey. The first byte depends is a 0x02 byte
/// if the y-coordinate is the lexicographically largest of the two associated with
/// the x-coordinate. Otherwise the first byte is a 0x03.
/// This prefix is followed with the x-coordinate.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PubKey {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for PubKey {
    const NAME: &'static str = "PubKey";
    const PACKAGE: &'static str = "cosmos.crypto.secp256k1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.crypto.secp256k1.PubKey".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.crypto.secp256k1.PubKey".into()
    }
}
/// PrivKey defines a secp256k1 private key.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct PrivKey {
    #[prost(bytes = "vec", tag = "1")]
    pub key: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for PrivKey {
    const NAME: &'static str = "PrivKey";
    const PACKAGE: &'static str = "cosmos.crypto.secp256k1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.crypto.secp256k1.PrivKey".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.crypto.secp256k1.PrivKey".into()
    }
}
include!("cosmos.crypto.secp256k1.serde.rs");
// @@protoc_insertion_point(module)
