// @generated
// This file is @generated by prost-build.
/// Module is the config object of the circuit module.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Module {
    /// authority defines the custom module authority. If not set, defaults to the governance module.
    #[prost(string, tag = "1")]
    pub authority: ::prost::alloc::string::String,
}
impl ::prost::Name for Module {
    const NAME: &'static str = "Module";
    const PACKAGE: &'static str = "cosmos.circuit.module.v1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.circuit.module.v1.Module".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.circuit.module.v1.Module".into()
    }
}
include!("cosmos.circuit.module.v1.serde.rs");
// @@protoc_insertion_point(module)
