// @generated
// This file is @generated by prost-build.
/// StoreKVPair is a KVStore KVPair used for listening to state changes (Sets and Deletes)
/// It optionally includes the StoreKey for the originating KVStore and a Boolean flag to distinguish between Sets and
/// Deletes
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreKvPair {
    /// the store key for the KVStore this pair originates from
    #[prost(string, tag = "1")]
    pub store_key: ::prost::alloc::string::String,
    /// true indicates a delete operation, false indicates a set operation
    #[prost(bool, tag = "2")]
    pub delete: bool,
    #[prost(bytes = "vec", tag = "3")]
    pub key: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes = "vec", tag = "4")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for StoreKvPair {
    const NAME: &'static str = "StoreKVPair";
    const PACKAGE: &'static str = "cosmos.store.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.store.v1beta1.StoreKVPair".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.store.v1beta1.StoreKVPair".into()
    }
}
/// BlockMetadata contains all the abci event data of a block
/// the file streamer dump them into files together with the state changes.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct BlockMetadata {
    #[prost(message, optional, tag = "6")]
    pub response_commit: ::core::option::Option<::tendermint_proto::abci::ResponseCommit>,
    #[prost(message, optional, tag = "7")]
    pub request_finalize_block:
        ::core::option::Option<::tendermint_proto::abci::RequestFinalizeBlock>,
    /// TODO: should we renumber this?
    #[prost(message, optional, tag = "8")]
    pub response_finalize_block:
        ::core::option::Option<::tendermint_proto::abci::ResponseFinalizeBlock>,
}
impl ::prost::Name for BlockMetadata {
    const NAME: &'static str = "BlockMetadata";
    const PACKAGE: &'static str = "cosmos.store.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.store.v1beta1.BlockMetadata".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.store.v1beta1.BlockMetadata".into()
    }
}
/// CommitInfo defines commit information used by the multi-store when committing
/// a version/height.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitInfo {
    #[prost(int64, tag = "1")]
    pub version: i64,
    #[prost(message, repeated, tag = "2")]
    pub store_infos: ::prost::alloc::vec::Vec<StoreInfo>,
    #[prost(message, optional, tag = "3")]
    pub timestamp: ::core::option::Option<::tendermint_proto::google::protobuf::Timestamp>,
}
impl ::prost::Name for CommitInfo {
    const NAME: &'static str = "CommitInfo";
    const PACKAGE: &'static str = "cosmos.store.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.store.v1beta1.CommitInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.store.v1beta1.CommitInfo".into()
    }
}
/// StoreInfo defines store-specific commit information. It contains a reference
/// between a store name and the commit ID.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StoreInfo {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub commit_id: ::core::option::Option<CommitId>,
}
impl ::prost::Name for StoreInfo {
    const NAME: &'static str = "StoreInfo";
    const PACKAGE: &'static str = "cosmos.store.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.store.v1beta1.StoreInfo".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.store.v1beta1.StoreInfo".into()
    }
}
/// CommitID defines the commitment information when a specific store is
/// committed.
#[allow(clippy::derive_partial_eq_without_eq)]
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CommitId {
    #[prost(int64, tag = "1")]
    pub version: i64,
    #[prost(bytes = "vec", tag = "2")]
    pub hash: ::prost::alloc::vec::Vec<u8>,
}
impl ::prost::Name for CommitId {
    const NAME: &'static str = "CommitID";
    const PACKAGE: &'static str = "cosmos.store.v1beta1";
    fn full_name() -> ::prost::alloc::string::String {
        "cosmos.store.v1beta1.CommitID".into()
    }
    fn type_url() -> ::prost::alloc::string::String {
        "/cosmos.store.v1beta1.CommitID".into()
    }
}
include!("cosmos.store.v1beta1.serde.rs");
// @@protoc_insertion_point(module)
